### ISSUE TITLE
-o host_iface option is ignored

### ISSUE THREAD

**Issue by YujiOshima** [gopher-net/ipvlan-docker-plugin#21]
To create new network attaching non-default host interface(e.g. eth2, vlan100), setting host_iface option like `docker network  create  -d ipvlan -o host_iface=[interface name]`.
host_iface value is assigned `n.ifaceOpt`.
https://github.com/gopher-net/ipvlan-docker-plugin/blob/master/plugin/ipvlan/driver.go#L293
But n.ifaceOpt is not used anywhere.
Ipvlan interfaces are always assigned default host interface (`ipVlanEthIface`).
https://github.com/gopher-net/ipvlan-docker-plugin/blob/master/plugin/ipvlan/driver.go#L304

**Comment by nerdalert** [comment]
Hey Yoshi! Sorry about that, it is old before you could pass generic k/v options to libnetwork. I cleaned it up with a patch in a few. Since each network is unique vs. a global option for multi-network when you create a network we can pass `-o host_iface=eth1` etc.

Full network create example `$ docker network  create  -d ipvlan  --subnet=192.168.1.0/24 --gateway=192.168.1.1 -o host_iface=eth1 -o mode=l2  net1`

**Comment by YujiOshima** [comment]
Thank you @nerdalert , but it looks still ignored `-o host_iface` option...
I fix that bug!
