### ISSUE TITLE
Kernel setup

### ISSUE THREAD

**Issue by mbdas** [gopher-net/ipvlan-docker-plugin#4]
Could you share what kind of kernel and OS version you are using for this ipvlan project?
One of our engineers mentioned ubuntu 14.04 can be upgraded to 3.19 to get the kernel support but user space tools were broken. So, it would be nice to know the setup to give this solution a try.

**Comment by orivej** [comment]
Indeed, the system in #3 is Ubuntu 14.04 with Linux 3.19.

**Comment by nerdalert** [comment]
Great point, thanks @mbdas I am on 4.2. I'm 99% positive I tested it on 4.05 and maybe ~4.0ish. Feel free to update the README or anything else that helps. I will update tonight otherwise. Appreciate it and any feedback is appreciated. @orivej issue #3 is great. 
- FYI, There is one big caveat and that is if the plugin restarts the network ID isn't stored persistently. In OVS we can just cache it in the ovsdb bridge table in a external_id/options column. Most of the issues in the OVS plugin are applicable here. Will get them added in case anyone feels like hacking on them w/us.
- Kernel ver and copy/paste install:

```
(='o'=)[root@ub-148:~$]# uname -a
Linux ub-148 4.2.0-040200rc3-generic #201507192329 SMP Sun Jul 19 22:32:13 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Copy/paste time saver:

```
wget http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.2-rc2-unstable/linux-headers-4.2.0-040200rc2_4.2.0-040200rc2.201507160938_all.deb

wget http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.2-rc2-unstable/linux-headers-4.2.0-040200rc2-generic_4.2.0-040200rc2.201507160938_amd64.deb

wget http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.2-rc2-unstable/linux-image-4.2.0-040200rc2-generic_4.2.0-040200rc2.201507160938_amd64.deb

sudo dpkg -i linux-headers-4.2*.deb linux-image-4.2*.deb

sudo reboot
```

Cheers and thanks,

**Comment by mbdas** [comment]
Yes would be great to have both the env setup and issue list updated. There is very good chance we will have engineers jointly hacking it.

Thx

**Comment by nerdalert** [comment]
Added to readme, thanks guys!
